{
  "headers": {
    "client_id": "1234",
    "client_secret": "1234",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "252de8e1-f58a-4ea3-9303-d2265805295a",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "458"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/request-access",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/request-access",
  "listenerPath": "/api/*",
  "relativePath": "/api/request-access",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/request-access",
  "rawRequestPath": "/api/request-access",
  "remoteAddress": "/127.0.0.1:62734",
  "requestPath": "/api/request-access"
}