#%RAML 1.0 DataType
displayName: Environment Details
type: object
properties:
  app_name: string
  access_token: string
  env_id: string
  log_level: string
  package_name: string

example: !include ../examples/approve-request-req.json