#%RAML 1.0 DataType
displayName: Log from audit log
description: Displays a log from audit log of portal
type: object
properties:
  log_id: number
  log: string
  logdatetime: string

example: !include ../examples/log-type.json