#%RAML 1.0 DataType
displayName: Login Credentials
description: Username and password of user
type: object
properties:
  username: string
  password: string

example: !include ../examples/login-cred.json