#%RAML 1.0 DataType
displayName: Request
description: Request for user
type: object
properties:
  approve: boolean
  request_id: number
  request_state: string
  team: string
  env_type: string
  env_id: string
  organization_name: string	
  app_name: string	
  package_name: string	
  user_name: string	
  user_id: string	
  log_level: string	
  request_to: string