{
  "headers": {
    "client_id": "1223",
    "client_secret": "1234",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "b9c03ba6-667c-4d60-96db-ecb5379d1b79",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "72"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/user-login",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/user-login",
  "listenerPath": "/api/*",
  "localAddress": "/127.0.0.1:8081",
  "relativePath": "/api/user-login",
  "uriParams": {},
  "rawRequestUri": "/api/user-login",
  "rawRequestPath": "/api/user-login",
  "remoteAddress": "/127.0.0.1:55834",
  "requestPath": "/api/user-login"
}