{
  "headers": {
    "client_id": "1223",
    "client_secret": "1234",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "21d5d5e8-3b5a-448f-b49b-129d2053a77f",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "75"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/user-login",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/user-login",
  "listenerPath": "/api/*",
  "relativePath": "/api/user-login",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/user-login",
  "rawRequestPath": "/api/user-login",
  "remoteAddress": "/127.0.0.1:60173",
  "requestPath": "/api/user-login"
}