{
  "headers": {
    "content-type": "application/json; charset=utf-8",
    "date": "Fri, 01 Jul 2022 15:23:55 GMT",
    "etag": "W/\"437-MMu7xJ2va8oxmtIGkMaIiLwNGlI\"",
    "expires": "-1",
    "pragma": "no-cache",
    "server": "nginx",
    "set-cookie": "_csrf=Sc6TZaAFpMLbecyah8bsAFPh; Path=/; HttpOnly; Secure",
    "set-cookie": "XSRF-TOKEN=oy50eESX-cl251uVzm4xKA5FwUjO6MfoixP8; Path=/; Secure",
    "set-cookie": "_csrf=YJCljoQtb9aoDy_Uuw3Vufid; Path=/; HttpOnly; Secure",
    "strict-transport-security": "max-age=31536000; includeSubDomains",
    "vary": "Accept-Encoding",
    "x-anypnt-trx-id": "0a3f17cf-2b9e-49b3-8360-ff81a7a1611f",
    "x-content-type-options": "nosniff",
    "x-dns-prefetch-control": "off",
    "x-download-options": "noopen",
    "x-envoy-decorator-operation": "authentication-server.access-management.svc.cluster.local:3004/*",
    "x-envoy-upstream-service-time": "107",
    "x-frame-options": "SAMEORIGIN",
    "x-frame-options": "SAMEORIGIN",
    "x-ratelimit-limit": "400",
    "x-ratelimit-remaining": "398",
    "x-ratelimit-reset": "1656689040",
    "x-request-id": "0a3f17cf-2b9e-49b3-8360-ff81a7a1611f",
    "x-xss-protection": "1; mode=block",
    "content-length": "1079",
    "connection": "keep-alive"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}