{
  "headers": {
    "content-type": "application/json; charset=utf-8",
    "date": "Fri, 01 Jul 2022 15:24:09 GMT",
    "etag": "W/\"437-gdI9DbHRUK2DmzQWI/jyetnjB7E\"",
    "expires": "-1",
    "pragma": "no-cache",
    "server": "nginx",
    "set-cookie": "_csrf=TbizkagLbxxRWF1pCf2jo1dS; Path=/; HttpOnly; Secure",
    "set-cookie": "XSRF-TOKEN=dR4NkZaP-q3kPqP1xYDHdRCWDFZOZBvzmVAk; Path=/; Secure",
    "set-cookie": "_csrf=8a_2ob78mBwLpymbe4ul9pCi; Path=/; HttpOnly; Secure",
    "strict-transport-security": "max-age=31536000; includeSubDomains",
    "vary": "Accept-Encoding",
    "x-anypnt-trx-id": "96fa541c-ec31-4851-88d6-a903239c96c5",
    "x-content-type-options": "nosniff",
    "x-dns-prefetch-control": "off",
    "x-download-options": "noopen",
    "x-envoy-decorator-operation": "authentication-server.access-management.svc.cluster.local:3004/*",
    "x-envoy-upstream-service-time": "92",
    "x-frame-options": "SAMEORIGIN",
    "x-frame-options": "SAMEORIGIN",
    "x-ratelimit-limit": "400",
    "x-ratelimit-remaining": "399",
    "x-ratelimit-reset": "1656689100",
    "x-request-id": "96fa541c-ec31-4851-88d6-a903239c96c5",
    "x-xss-protection": "1; mode=block",
    "content-length": "1079",
    "connection": "keep-alive"
  },
  "reasonPhrase": "OK",
  "statusCode": 200
}